packages:
  - 'backend'
  - 'frontend'
  # Nanti kita bisa tambah '- shared' kalau ada tipe data/utilitas yang dipakai berdua
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
